matrix_to_csv(DO1_out, "Domain1corr.txt")
matrix_to_csv(DO2_out, "Domain2corr.txt")
matrix_to_csv(DO3_out, "Domain3corr.txt")
matrix_to_csv(DO5_out, "Domain5corr.txt")
matrix_to_csv(DO6_out, "Domain6corr.txt")
matrix_to_csv(DO7_out, "Domain7corr.txt")
matrix_to_csv(DO8_out, "Domain8corr.txt")
matrix_to_csv(DO9_out, "Domain9corr.txt")
matrix_to_csv(DO10_out, "Domain10corr.txt")
matrix_to_csv(DO11_out, "Domain11corr.txt")
matrix_to_csv(DO12_out, "Domain12corr.txt")
matrix_to_csv(DO13_out, "Domain13corr.txt")
matrix_to_csv(DO14_out, "Domain14corr.txt")
matrix_to_csv(DO15_out, "Domain15corr.txt")
matrix_to_csv(DO16_out, "Domain16corr.txt")
matrix_to_csv(DO17_out, "Domain17corr.txt")
matrix_to_csv(cont_out, "contcorr.txt")

